server:
  port: 8100

spring:
  application:
    name: fiz-gateway

# eureka server url
#  eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8314/eureka/
